scenery = ['Los Angeles','Paris','London','Hawaii']
print(scenery)
print(sorted(scenery))
print(scenery)
print(sorted(scenery,reverse=True))
print(scenery)
scenery.reverse()
print(scenery)
scenery.reverse()
print(scenery)
scenery.sort()
print(scenery)
scenery.sort(reverse=True)
print(scenery)